server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///store?serverTimezone=UTC
    username: root
    password: 12356
  application:
    name: service-provide   # 配置微服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka    # 配置服务器地址
  instance:
    lease-renewal-interval-in-seconds: 5  # 心跳间隔时间
    lease-expiration-duration-in-seconds: 15  # 心跳过期时间